title: JDeferred
description: Java Deferred / Promise library
google_analytics: UA-7701209-6
show_downloads: false
theme: jekyll-theme-slate

github:
  repository_url: https://github.com/jdeferred/jdeferred

gems:
  - jekyll-mentions
